### ISSUE TITLE
Display runtime error message in server side and pass it to the client

### ISSUE THREAD

**Issue by atifkarim** [faaxm/exmpl-cmake-grpc#4]
I need to set some value from client where the user could set wrong value and server should warn them. At least, I need to see the error message in server side console. But I am not getting how to achieve it.

I have modified some of your code.
`addressbook.proto`
```
message NameQuerry {
    string name = 1;
    int32 cl_value = 2;
}
```

`client/src/main.cpp`
```cpp
int main(int argc, char* argv[])
{
    // Setup request
    expcmake::NameQuerry query;
    expcmake::Address result;
    query.set_name("John");

    int x;
    cout << "give value of x: ";
    cin>> x;
    query.set_cl_value(x);

   // remaining are as like as before
```

`server/src/main.cpp`
```cpp
#include <iostream>
using namespace std;

void Check_Value(const ::expcmake::NameQuerry* request)
{
    if (request->cl_value() < 5)
		cout << "request->cl_value(): " << request->cl_value() << endl;
	else
		throw std::runtime_error("********** BAD VALUE **********");
}

class AddressBookService final : public expcmake::AddressBook::Service {
    public:
        virtual ::grpc::Status GetAddress(::grpc::ServerContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response)
        {
            std::cout << "Server: GetAddress for \"" << request->name() << "\"." << std::endl;
            Check_Value(request);

        // remaining are as like as before
```

After building the project if from client side `5` or greater than `5` is given `server` didn't show any message where my expectation was it should print
> ********** BAD VALUE **********

Though, in client side I have got all passed value as `BLANK` where I can assume that, `server` didn't perform any process after the `runtime_error`.

So my query is:
1/ How can I see the `runtime_error` message in server side console?
2/ Any `gRPC default system` to pass this incident to the client (Any generic message).

`Note:` In my real example this `runtime_error` message related function is coming from another project where I cannot access to modify.

**Comment by faaxm** [comment]
I believe you will have to implement this yourself by having the server reply with a certain message that contains the error.

However, since this is a general question on gRPC and not an issue with the code in this repository, I think you should rather ask this question on a site such as https://stackoverflow.com, as I do not have the time currently to look into this in detail.
